[package]
name = "engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mdxt = "0.5.3"
tera = "1.17"
grass = "0.11"
yaml-rust = "0.4.5"
lazy_static = "1.4.0"
linked-hash-map = "*"
hxml = "0.1.0"