[package]
name = "engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mdxt = "*"
tera = "1.16"
grass = "0.11"
yaml-rust = "0.4.5"